### ISSUE TITLE
shards expects releases to have tag names prefixed "v"

### ISSUE THREAD

**Issue by slowernet** [soveran/ohm-crystal#4]
```
app (master)$ crystal deps
Updating https://github.com/soveran/ohm-crystal.git
git command failed: git ls-tree -r --full-tree --name-only v0.2.0 -- shard.yml (). Maybe a commit, branch or file doesn't exist?
```

https://github.com/crystal-lang/shards#usage:
>When libraries are installed from Git repositories, the repository is expected to have version tags following the semver format, prefixed with a v. Examples: v1.2.3 or v2.0.0-rc1.

Thanks for all the Crystal work, @soveran!

**Comment by soveran** [comment]
@slowernet Fixed! As I use the master branch directly I hadn't noticed, so thanks a lot for letting me know about this. I'll update the tags in the other projects. Thanks!
